global:
    scrape_interval: 5s
    external_labels:
        monitor: 'cherry'
scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['localhost:9090']
    - job_name: 'cherry-metrics'
      scrape_interval: 5s
      static_configs:
          - targets: ['localhost:5000']